<?php
/**
 * Created by PhpStorm.
 * User: CASA
 * Date: 29/10/2017
 * Time: 10:44 PM
 */

class Proyecto_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    public function guardarProyecto($data){

    }

    public function __get($key)
    {
        return parent::__get($key); // TODO: Change the autogenerated stub
    }


}